ROOT=../../..
WIN32EX=$(ROOT)/../Win32Ex
OS=linux32
include $(WIN32EX)/project/CommonMakefiles/common.Makefile
LDFLAGS=-lWin32Ex$(OUTPUT_SUFFIX) -lpthread -L $(WIN32EX)/lib
include $(ROOT)/project/src.Makefile
